### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by sack2116** [saadahmad5/BulkHtmlEmailSender#1]
hi, can you explain how this is use or ran?
 which file do i execute?

**Comment by saadahmad5** [comment]
This is a Visual Studio solution. Please download and install Visual Studio 2019 or newer and run the .sln file which will open the solution.

**Comment by sack2116** [comment]
hi can one create a json file with the path to the Dist list and template... and perhaps hardcode the email address and password in json?..





[cid:a760fb41-aee1-40a0-b2bd-88cce8775c7e]

Isaac Dominguez

Microsoft Certified Systems Administrator

[cid:19d4100d-4199-4b63-854d-730b48d821c3]

Mobile: 401-<tel:401-688-2119>243-3200

Email:   ***@***.***>***@***.***

[cid:e0e96c62-a7b8-4df2-8430-16b3e09c4c9f]    [cid:a4abf914-59d7-4169-b9da-a990e12d8e39]     [cid:5bc27b0b-7789-4f23-a45d-ef3a7ff668f5]     [cid:fa0fb41c-0749-43ed-8f29-8b6e6bf0760f]




________________________________
